name: CI-TEST-SELENIUM

on:
  push:
    branches: ['*']
  pull_request:
    branches: [develop, qa, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libglib2.0-0 \
            libxrandr2 \
            libxss1 \
            libgconf-2-4 \
            libgtk-3-0 \
            libxshmfence1 \
            libasound2 \
            fonts-liberation \
            libappindicator3-1 \
            xdg-utils \
          google-chrome-stable

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Start Xvfb
        run: |
              Xvfb :99 -screen 0 1920x1080x16 &
              export DISPLAY=:99

      - name: Run tests
        env:
          DISPLAY: :99
        run: |
          pytest -m regression --browser=chrome --alluredir=allure_results

      - name: Upload allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure_results

  merge:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge pull request
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        curl -s -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge" \
          -d '{"commit_title":"Auto-merged by GitHub Actions","merge_method":"merge"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}